==========================
MACS Replicated Intervals
==========================

Replicated intervals were generated by first merging the intervals from all biological replicates for each tissue 
and then removing merged intervals that did not overlap with at least one original interval in each replicate. 
The following table presents the number of intervals found in all replicates of each tissue:

.. report:: macs_replicated_intervals.replicatedIntervalSummary
   :render: table

   MACS replicated interval summary

Interval Length
===============

The following plot shows the distribution of interval length for replicated intervals:

.. report:: macs_replicated_intervals.replicatedIntervalLengths
   :render: line-plot
   :transform: histogram
   :groupby: all
   :logscale: x
   :tf-aggregate: normalized-total
   :as-lines:

   Distribution of replicated interval lengths


Interval Coverage
=================

Average Coverage
----------------

The following plot shows the distribution of average interval coverage for replicated intervals across multiple BAM files.
The average coverage is the average number of reads covering each base the interval.

.. report:: macs_replicated_intervals.replicatedIntervalAverageValues
   :render: line-plot
   :transform: histogram
   :groupby: all
   :tf-range: 0,100
   :tf-aggregate: normalized-total,reverse-cumulative
   :as-lines:

   Distribution of the average number of reads
   matching to bins within an interval.

Maximum Coverage
----------------

The following plot shows the maximum interval coverage for replicated intervals across multiple BAM files.
The maximum coverage is the maximum number of reads falling into the
bins that constitute an interval. The interval peak is the position with the maximum
number of reads.

.. report:: macs_replicated_intervals.replicatedIntervalPeakValues
   :render: line-plot
   :transform: histogram
   :groupby: all
   :tf-range: 0,200
   :tf-aggregate: normalized-total,reverse-cumulative
   :as-lines:

   Distribution of the number of reads at the peak within an interval.
   The proportion of intervals of a certain peak value or more.

Interval Fold Change
====================

The following plot shows the distribution of the fold change for each dataset.
The fold change is the enrichment of reads within the interval compared to the input sample or to local background.

.. report:: macs_replicated_intervals.replicatedIntervalFoldChange
   :render: line-plot
   :transform: histogram
   :groupby: all
   :tf-range: 0,50
   :tf-aggregate: normalized-total,reverse-cumulative
   :as-lines:

   Distribution of the fold change per interval


CpG Density
===========

The following plot shows the distribution of CpG density for each set.

.. report:: macs_replicated_intervals.replicatedIntervalCpGDensity
   :render: line-plot
   :transform: histogram
   :tf-aggregate: normalized-total
   :groupby: all
   :as-lines:
   :xtitle: CpG density
   :layout: column-3

   Distribution of CpG density


CpG Observed/Expected
=====================

The following plots show the distribution of observed/expected CpGs for each set.
The expected number of CpG dinucleotides was calculated as the product of the number of C and G nucleotides 
in the interval divided by the interval length as in Emboss cpgplot.
The control dataset was generated by taking an interval of the same size 10kb upstream of the CpG island.

.. report:: macs_replicated_intervals.replicatedIntervalCpGObsExp2
   :render: line-plot
   :transform: histogram
   :tf-aggregate: normalized-total
   :groupby: all
   :xrange: 0,2
   :as-lines:
   :xtitle: CpG Observed/Expected
   :layout: column-3

   Distribution observed/expected CpGs (expected = nC*nG/length)


GC Content
==========

The following plot shows the distribution of GC content for each set.

.. report:: macs_replicated_intervals.replicatedIntervalGCContent
   :render: line-plot
   :transform: histogram
   :tf-aggregate: normalized-total
   :groupby: all
   :as-lines:
   :xtitle: GC content
   :layout: column-3

   Distribution of GC content

Peak location
=============

The following plot shows the distribution of the peak location within
an interval for each set, i.e. is it on the sides or the middle
of an interval. Note that this counting does not take into account
strandedness.

.. report:: macs_replicated_intervals.replicatedIntervalPeakLocation
   :render: line-plot
   :transform: histogram
   :groupby: all
   :tf-aggregate: normalized-total
   :as-lines:
  
   Distance of peak towards start/end of interval normalized
   by the size of the interval.

The following plot shows the distribution of the peak distance within
an interval for each set, i.e. is it on the sides or the middle
of an interval. Note that this counting does not take into account
strandedness.

.. report:: macs_replicated_intervals.replicatedIntervalPeakDistance
   :render: line-plot
   :transform: histogram
   :groupby: all
   :logscale: x
   :tf-aggregate: normalized-total
   :as-lines:
  
   Distance of peak towards start/end of interval


