#!/bin/bash
##
## csort [unix sort options] < stdin
## 
## This script allows you to apply unix sort to a file without 
## disturbing a header or comments at the beginning of file. 
## Column names can be given alphanumerically if enclosed in
## colons.
##
## example: 
##   csort -k:colum:n < in
## 
## will sort standard input on column "column" numerically.

sorter=$*;

awk  -v sorter="${sorter}" \
    "BEGIN { take=-1; ix=0; x=0; offset=1; \
     while(1) { ix=match( substr(sorter,offset),\":[^:]+:\"); \
     	      if (ix==0) {break;} \
	      fields[++x]=substr(sorter,offset+RSTART,RLENGTH-2); offset=offset+RSTART+RLENGTH ; }\
     } \
     take >= 0 { print | cmd; next } \
     /^#/ { print; next; } \
     { print; ++take; \
       for (x in fields) { \
           for (f=1;f<=NF;++f) { if (\$f == fields[x]) break; } \
       	   gsub( \":[^:]+:\", sprintf(\"%i\", f), sorter ); }
       cmd=sprintf(\"sort %s \", sorter); } \
     END{ close(cmd); }" 
