#!/bin/bash

# A simple bash script to sort gff files
# For sorting by gene, the script assumes that the 
# the first identifier in the attribute field is the gene.

case "$1" in
  gene    ) ssort="-k1,1 -k9,9";;
  pos     ) ssort="-k1,1 -k4,4n";;
  genepos ) ssort="-k1,1 -k9,9 -k4,4n";;
  *       ) ssort="-k1,1 -k9,9 -k4,4n";;
esac

sort -t "	" $ssort 
