#!/bin/bash
##
## hsort nlines [unix sort options] < stdin
## 
## This script allows you to apply unix sort to a file without 
## disturbing a header or comments at the beginning of a file.
##
## Comment lines begin either with a # or @. They will all end up
## at the beginning of the sorted file. They are not counted for nlines.
##
## The first nlines lines are ignored and the input has to be
## piped in.

hlines=$1;
shift;

awk  -v hlines=${hlines} "BEGIN {take=-hlines; cmd=sprintf(\"sort $* \"); } \
     /^[#@]/ { print; next; } \
     take >= 0 { print | cmd; next } \
     { print; ++take; next } 
     END{ close(cmd); }"
    


