
peptides.transcripts: peptides.fasta
	grep ">" peptides.fasta | perl -pe "s/>//g; s/[\t ]+\S*//" | cut -f 1 | sort | uniq > $@

all.transcripts: all.predictions
	grep -v "#" all.predictions | cut -f 2 | sort | uniq > $@

all.missed_transcripts: peptides.transcripts all.transcripts
	diff all.transcripts peptides.transcripts |\
	 grep ">" | perl -pe "s/> //" > $@
