################################################################################
#   Gene prediction pipeline 
#
#   $Id: Makefile.analyze_codonbias_duplications 2781 2009-09-10 11:33:14Z andreas $
#
#   Copyright (C) 2004 Andreas Heger
#
#   This program is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License
#   as published by the Free Software Foundation; either version 2
#   of the License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#################################################################################
##
## Compare a sequence property from the codonbias table (codonbias/gc3_4d/...) 
## between the duplicated proteins and 1:1 orthologs.
##
#################################################################################
SHELL=/bin/bash --login

LOG=log

################################################
## Section parameters: start
################################################
## project name
PARAM_PROJECT_NAME?=analyze_codonbias_duplications
################################################
## directories
## directory where gene prediction scripts can be found
DIR_SCRIPTS_GENEPREDICTION?=/home/andreas/gpipe/
## directory where various helper scripts can be found
DIR_SCRIPTS_TOOLS?=/net/cpp-group/scripts/tools/
## shared directory, path for submit host
DIR_TMP_SHARED_LOCAL?=/net/cpp-group/gpipe/tmp/$(PARAM_PROJECT_NAME)/
## shared directory, path for cluster node
DIR_TMP_SHARED_REMOTE?=/net/cpp-group/gpipe/tmp/$(PARAM_PROJECT_NAME)/

## Directory to upload summary pages.
PARAM_DIR_UPLOAD?=/home/andreas/uploads/

################################################
## Database connection parameters
## database
PARAM_PSQL_DATABASE?=andreas
## host
PARAM_PSQL_HOST?=db
## user
PARAM_PSQL_USER?=andreas
## schema
PARAM_PSQL_SCHEMA?=$(PARAM_PROJECT_NAME)

################################################
## genome parameters

## number of genomes to use
PARAM_NUM_GENOMES?=`echo $(PARAM_SRC_SCHEMAS) | wc -w`

## id of master genome
PARAM_GENOME_MASTER?=dmel_vs_dmel3

## pattern to identify master genome
PARAM_INPUT_GENOME_MASTER?=^$(PARAM_GENOME_MASTER)

## pattern to extract genome from identifier
PARAM_INPUT_GENOME?=^([^$(PARAM_SEPARATOR)]+)[^$(PARAM_SEPARATOR)]

################################################
## directories and database schemas
## IMPORTANT: Add new entries to the end for update to work

## schemas in input
PARAM_SRC_SCHEMAS?=dmel_vs_dmel3 dsim_vs_dmel5 dsec_vs_dmel2 dyak_vs_dmel6 dere_vs_dmel5 dana_vs_dmel5 dpse_vs_dmel7 dper_vs_dmel2 dvir_vs_dmel5 dmoj_vs_dmel5 dgri_vs_dmel4

## These should be sorted in the same way.
PARAM_SRC_DIRS?=$(PARAM_SRC_SCHEMAS)

## separator in identifier
PARAM_SEPARATOR?=|

## names of genomes (for export)
PARAM_SRC_NAMES?=$(shell echo "$(PARAM_SRC_SCHEMAS)" | perl -p -e "s/_vs_dmel//g")

################################################
## various things I need to put somewhere.
PARAM_SRC_DIR?=../../orthology_pairwise_1v4/analysis.dir/

################################################
PARAM_BIAS?=cai

################################################
# Section parameters: end
################################################

################################################
## some commands for dealing with psql

## extracting prefix for table name
CMD_TABLE_PREFIX=`echo $* | perl -p -e "s/\./_/g"`


GENOMES_COMMA=`echo '$(PARAM_SRC_SCHEMAS)' | perl -p -e 's/ +/,/g'`
NAMES_COMMA=`echo '$(PARAM_SRC_NAMES)' | perl -p -e 's/ +/,/g'`

sets.prepare:
	$(PRELOG)
	@rm -f *.{bg,fg}
	@for genome1 in $(PARAM_SRC_SCHEMAS); do \
		for genome2 in $(PARAM_SRC_SCHEMAS); do \
			if [ "$${genome1}" != "$${genome2}" ]; then \
				awk -v genome1=$${genome1} -v genome2=$${genome2} \
				'BEGIN { file1=sprintf("%s-%s.bg", genome1, genome2); \
					 file2=sprintf("%s-%s.fg", genome1, genome2); }\
				$$1 !~ genome1 || $$3 !~ genome2 { next; } \
				$$4 == "1:1" { printf("%s\n", $$2) >> file1; next} \
				$$4 != "1:1" { printf("%s\n", $$2) >> file2; next}'\
				< $(PARAM_SRC_DIR)orthologs_second.list; \
			fi; \
		done; \
	done
	@touch $@
	$(EPILOG)

prepare: create-log sets.prepare maps.prepare

maps.prepare:
	$(PRELOG)
	@rm -f *.chunk
	@for x in $(PARAM_SRC_SCHEMAS); do \
		$(PSQL_CONNECTION) "SELECT prediction_id,$(PARAM_BIAS) FROM $${x}.codonbias" $(PSQL_CONNECTION_OPTIONS) > $${x}.map; \
	done
	@for genome1 in $(PARAM_SRC_SCHEMAS); do \
		for genome2 in $(PARAM_SRC_SCHEMAS); do \
			if [ "$${genome1}" != "$${genome2}" ]; then \
				touch pair_$${genome1}-$${genome2}.chunk; \
			fi; \
		done; \
	done
	@touch $@
	$(EPILOG)

all: dstncompare

##########################################################################
DSTNCOMPARE_QUERIES=$(wildcard pair_*.chunk)
DSTNCOMPARE_TARGETS=$(DSTNCOMPARE_QUERIES:%.chunk=%.dstncompare)

dstncompare: $(DSTNCOMPARE_TARGETS)

##########################################################################
%.dstncompare: %.chunk
	$(PRELOG)
	@p=`echo $* | perl -p -e "s/pair_//";`; \
	map=`echo $* | perl -p -e "s/pair_//; s/-.*//g" `; \
	python  $(DIR_SCRIPTS_TOOLS)r_compare_distributions.py \
	--method=ks \
	--hardcopy=$*.png \
	--infile1=$${p}.bg \
	--infile2=$${p}.fg \
	--infile-map=$${map}.map > $@
	$(EPILOG)

##########################################################################
## Build summary page for wiki
summary.wiki:
	$(PRELOG)
	@rm -f $@
	python $(DIR_SCRIPTS_TOOLS)preppy.py \
	$(DIR_SCRIPTS_GENEPREDICTION)analyze_codonbias_duplications_wiki.prep \
	genomes=$(GENOMES_COMMA) \
	> $@
	@mv -f summary.wiki $(PARAM_DIR_UPLOAD)
	@rm -f $(PARAM_DIR_UPLOAD)$@.zip
	@zip $(PARAM_DIR_UPLOAD)$@.zip *.png *.ps_* 2>/dev/null
	$(EPILOG)

##########################################################################
## How to make a picture out of a matrix
%.png: %.matrix
	@python $(DIR_SCRIPTS_TOOLS)plot_matrix.py \
	--headers --labels="Genomes","Genomes" \
	--hardcopy=$@ \
	< $*.matrix

##########################################################################
## Matrix of p-values
p_values.matrix:
	$(PRELOG)
	@grep "p.value" pair_*.dstncompare |\
	perl -p -e "s/.dstncompare:p.value//; s/pair_//; s/-/\t/;" |\
	python $(DIR_SCRIPTS_TOOLS)sparse2full.py \
	--titles \
	--asymmetric \
	--row-names="$(GENOMES_COMMA)" \
	--col-names="$(GENOMES_COMMA)" |\
	python $(DIR_SCRIPTS_TOOLS)matrix2matrix.py \
	--method=negzero2value,log \
	--value=1e-15 \
	--headers \
	> $@
	$(EPILOG)

##########################################################################
## Matrix of counts for duplications/deletions
## Use as fg.matrix/bg.matrix
fg.matrix bg.matrix:
	$(PRELOG)
	@f=$@; prefix=$${f%.matrix}; \
	wc -l *.$${prefix} |\
	awk '!/total/ { gsub( "[.].*", "", $$2); split($$2, a, "-") ; \
		printf("%s\t%s\t%s\n", a[1], a[2], $$1); } ' |\
	python $(DIR_SCRIPTS_TOOLS)sparse2full.py \
	--titles \
	--asymmetric \
	--row-names="$(GENOMES_COMMA)" \
	--col-names="$(GENOMES_COMMA)" > $@
	$(EPILOG)

##########################################################################
clean:
	rm -f *.png *.analysis *.chunk *.bg *.fg *.dstncompare *.map
	rm -f *.prepare

##########################################################################
include $(DIR_SCRIPTS_GENEPREDICTION)/makefiles/Makefile.common
