################################################################################
#   Gene prediction pipeline 
#
#   $Id: Makefile.step2 1764 2008-03-18 10:34:04Z andreas $
#
#   Copyright (C) 2004 Andreas Heger
#
#   This program is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License
#   as published by the Free Software Foundation; either version 2
#   of the License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#################################################################################

##############################################################################
##############################################################################
##############################################################################
## Clustering of peptides 
## This step has been substituted using the file $(PARAM_INPUT_MAP).
##############################################################################
step2: step1 representatives.fasta
	$(EPILOG)
	@touch $@

## build file with masked peptide sequences of representative sequences.
representatives.fasta: $(PARAM_INPUT_MAP) peptides_masked.fasta
	$(PRELOG)
	@grep -v "#" $(PARAM_INPUT_MAP) | cut -f 1 | uniq > $@_tmp
	@perl $(DIR_SCRIPTS_GENEPREDICTION)extract_fasta.pl $@_tmp < peptides_masked.fasta > $@
	@rm -f $@_tmp
	$(EPILOG)

## build file with masked peptide sequences of member sequences
members.fasta: $(PARAM_INPUT_MAP)
	$(PRELOG)
	@grep -v "#" $(PARAM_INPUT_MAP) | awk '$$1 != $$2' | cut -f 2 | uniq > $@_tmp
	@perl $(DIR_SCRIPTS_GENEPREDICTION)extract_fasta.pl $@_tmp < peptides_masked.fasta > $@
	@rm -f $@_tmp
	$(EPILOG)

## build a list of members
members.transcripts: members.fasta
	$(PRELOG)
	@grep ">" members.fasta | perl -pe "s/>//g; s/ .*//" | cut -f 1 |\
	sort | uniq > $@ 
	$(EPILOG)

## build a list of representatives
representatives.transcripts: representatives.fasta
	$(PRELOG)
	@grep ">" representatives.fasta | perl -pe "s/>//g; s/ .*//" | cut -f 1 |\
	sort | uniq > $@ 
	$(EPILOG)

## build a list of all transcripts
all.transcripts: peptides.fasta
	$(PRELOG)
	@grep ">" peptides.fasta | perl -pe "s/>//g" | cut -d " " -f 1 |\
	sort | uniq > $@ 
	$(EPILOG)

