## how to get exon boundaries

## from peptides.fasta and assuming, everything is a single exon

reference.exons: peptides.fasta
	awk 'BEGIN {size=0; id="";} \
		/>/ { if (id) { printf("%s\tchrU\t+\t1\t1\t%i\t%i\t0\t0\n", id, 0, size * 3); } \
			id = substr($$1,2); size = 0; next} \
		{ size+=length($$0); } \
	END { if (id) { printf("%s\tchrU\t+\t1\t1\t%i\t%i\t0\t0\n", id, 0, size * 3); } }' \
	< peptides.fasta > $@


