################################################################################
#   Gene prediction pipeline 
#
#   $Id: Makefile.sites_preparation 2781 2009-09-10 11:33:14Z andreas $
#
#   Copyright (C) 2005 Andreas Heger
#
#   This program is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License
#   as published by the Free Software Foundation; either version 2
#   of the License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#################################################################################
#################################################################################
#################################################################################
##
## Pre-processing alignments for building site-specific rate analysis
##
##
#################################################################################

#################################################################################
## Mask sequences and remove fully gapped columns
%.cleaned_fasta: %.fasta
	$(PRELOG)
	@if test -n "$(PARAM_MASK_MALI)"; then \
		python $(DIR_SCRIPTS_GENEPREDICTION)optic/prune_multiple_alignment.py \
			--log=$@.log \
			--exons=$*.exons \
			--master-species=$(PARAM_ANALYSIS_MASTER_SCHEMA) \
			--remove-stops \
			--remove-frameshifts \
			--split-exons \
			--mask-master \
			--verbose=2 \
		< $*.fasta |\
		python $(DIR_SCRIPTS_TOOLS)mali2mali.py \
			--method=remove-all-gaps \
			--verbose=0 \
		> $@_tmp1; \
		cat $@_tmp1 |\
		python $(DIR_SCRIPTS_TOOLS)fasta2fasta.py --method=translate -v 0 |\
		python $(DIR_SCRIPTS_TOOLS)fasta2fasta.py --method=mask-seg -v 0	> $@_tmp2; \
		python $(DIR_SCRIPTS_TOOLS)fasta2fasta.py \
			--method=mask-codons \
			--parameters=$@_tmp2 \
			--verbose=0 \
		< $@_tmp1 |\
		python $(DIR_SCRIPTS_TOOLS)mali2mali.py \
			--method=propagate-masks,remove-all-gaps \
			--mask-char="n" \
			--verbose=0 \
		> $@; \
		rm -f $@_tmp*; \
	else \
		cp $< $@; \
	fi
	$(EPILOG)

#################################################################################
%.kaks: %.cleaned_fasta
	$(PRELOG)
	@seq_pairs_kaks \
		--cdna_sequences $^ \
		--err_log $@.err \
		--allvsall \
		--aligned \
		--temp_directory /tmp/$@ \
	> $@
	$(EPILOG)

#################################################################################
%.phylip: %.cleaned_fasta
	$(PRELOG)
	@python $(DIR_SCRIPTS_TOOLS)fasta2fasta.py \
		--method="build-map" \
		--parameters=$*.map \
		--template-identifier="%i" \
		--verbose=0 \
	< $^ |\
	python $(DIR_SCRIPTS_TOOLS)mali2mali.py \
		--output-format=phylip \
		--verbose=0 \
	> $@
	$(EPILOG)

%.tree: %.kaks
	$(PRELOG)
	@cut -f 1,2,4 $^ |\
	tree_fitch \
	-i p \
	--err_log $@.err \
	> $@
	$(EPILOG)

%.ptree: %.tree %.phylip
	$(PRELOG)
	@python $(DIR_SCRIPTS_TOOLS)tree2tree.py \
		--method=rename \
		--parameter=$*.map \
		--verbose=0 \
	< $*.tree > $@
	$(EPILOG)

.PRECIOUS: %.phylip %.ptree %.kaks %.tree %.sites.prepare %.sites.run %.cleaned_fasta


