################################################################################
#   Gene prediction pipeline 
#
#   $Id: Makefile.orthology_step2 2781 2009-09-10 11:33:14Z andreas $
#
#   Copyright (C) 2004 Andreas Heger
#
#   This program is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License
#   as published by the Free Software Foundation; either version 2
#   of the License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#################################################################################

################################################
## step0: run blast all vs all
STEP2_QUERIES=$(wildcard step2_*.chunk)
STEP2_TARGETS=$(STEP2_QUERIES:%.chunk=%.links)

step2: step2.prepare step2.run step2.finish 
	@touch $@

step2.run: step2.prepare
	$(CMD_LOG) "started $@"
	$(PARAM_CMD_COPY)map_token2id.fasta $(DIR_TMP_SHARED_LOCAL)
	$(MAKE) -C step2.dir -j $(PARAM_STEP2_NUMJOBS) -k $@-hook
	@touch $@
	@rm -f $(DIR_TMP_SHARED_LOCAL)map_token2id.fasta
	$(CMD_LOG) "finished $@"

.PHONY: step2.run-hook 

step2.prepare: map_rep2mem
	$(PRELOG)
	@$(MAKE) step2.dir
	@split -l $(PARAM_STEP2_CHUNKSIZE) -a 5 map_rep2mem step2.dir/step2_
	@for file in step2.dir/step2_*; do \
		mv $${file} $${file}.chunk; \
	done
	@touch $@
	$(EPILOG)

step2.run-hook: $(STEP2_TARGETS)

step2_%.links: step2_%.chunk
	@$(CMD_REMOTE_SUBMIT) align_pairs -r 10000 -v 2 -f $(DIR_TMP_SHARED_REMOTE)map_token2id.fasta < step2_$*.chunk > $@

step2.finish: map_mem2rep.links
	@touch $@
	@$(CMD_LOG) "Contents of map_mem2rep.links"
	@perl $(DIR_SCRIPTS_TOOLS)graph_howmany.pl < map_mem2rep.links $(TOLOG)
	$(EPILOG)

map_mem2rep.links: step2.run
	$(PRELOG)
	find step2.dir -name "*.links" -exec grep -v "#" {} \; > $@
	$(EPILOG)
