################################################################################
#   Gene prediction pipeline 
#
#   $Id: Makefile.orthology_prepare 2781 2009-09-10 11:33:14Z andreas $
#
#   Copyright (C) 2005 Andreas Heger
#
#   This program is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License
#   as published by the Free Software Foundation; either version 2
#   of the License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#################################################################################
prepare-prehook:
	-@mkdir data

prepare: create-log prepare-prehook data/transcripts.list data/exon_boundaries data/peptides.fasta data/cds.fasta 
	$(CMD_LOG) "transcripts:" `wc -l < data/transcripts.list`
	@cut -f 1 -d "|" data/transcripts.list | sort | uniq -c $(TOLOG) 
	$(CMD_LOG) "peptides:" `grep -c ">" data/peptides.fasta`
	@grep ">" data/peptides.fasta	|\
		perl -p -e "s/^>//" |\
		cut -f 1 -d "|" | sort | uniq -c $(TOLOG)
	$(CMD_LOG) "cds:" `grep -c ">" data/cds.fasta`
	@grep ">" data/cds.fasta	|\
		perl -p -e "s/^>//" |\
		cut -f 1 -d "|" | sort | uniq -c $(TOLOG)
	$(CMD_LOG) "exon_boundaries" `cut -f 1 data/exon_boundaries | sort | cut -f 1 | uniq | wc -l`
	@cut -f 1 -d "|" data/exon_boundaries | sort | uniq -c $(TOLOG)
	$(EPILOG)
	@touch $@

################################################
## collect input sets
data/transcripts.list:
	$(PRELOG)
	rm -f $@
	for dir in $(PARAM_SRC_DIRS); do \
		cat $${dir}/export_clustering.dir/export_clustering_nr_predictions >> $@; \
	done
	$(EPILOG)

data/exon_boundaries: 
	$(PRELOG)
	rm -f $@
	for dir in $(PARAM_SRC_DIRS); do \
		cat $${dir}/export_clustering.dir/export_clustering_exon_boundaries >> $@; \
	done
	$(EPILOG)

data/peptides.fasta: 
	$(PRELOG)
	rm -f $@
	for dir in $(PARAM_SRC_DIRS); do \
		cat $${dir}/export_clustering.dir/export_clustering_peptides.fasta >> $@; \
	done
	$(EPILOG)

data/cds.fasta: 
	$(PRELOG)
	rm -f $@
	for dir in $(PARAM_SRC_DIRS); do \
		cat $${dir}/export_clustering.dir/export_clustering_cds.fasta >> $@; \
	done
	$(EPILOG)

