################################################################################
#   Gene prediction pipeline 
#
#   $Id: Makefile.xrate_gc 2781 2009-09-10 11:33:14Z andreas $
#
#   Copyright (C) 2005 Andreas Heger
#
#   This program is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License
#   as published by the Free Software Foundation; either version 2
#   of the License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#################################################################################
#################################################################################
#################################################################################
## Analysis of kaks values using codeml
## 
## Given: 
##	a tree
##
## Statistical significance
##	codeml is run twice, 
##		once, with and once without specifying for w (branch specific ka/ks) to vary.
##
## Use a sample of PARAM_SAMPLE_SIZE genes.
#################################################################################

################################################
## Section parameters: start
################################################
## project name
PARAM_PROJECT_NAME?=geneprediction

################################################
## directory with Ian Holmes' perl scripts
DIR_SCRIPTS_IHTOOLS?=/net/cpp-group/scripts/ihtools/perl/

## Filename with src information using ks
PARAM_DIR_SRC_MALIS?=../malis/

## Pattern to find multiple alignments
PARAM_PATTERN_MALIS?=$(PARAM_DIR_SRC_MALIS)data.dir/cluster_%s.dir/cluster_%s.bl_mali

## File with tree information
PARAM_INPUT_FILENAME_TREES?=

################################################
## Number of genomes
PARAM_NUM_GENOMES?=`echo $(PARAM_SRC_SCHEMAS) | wc -w`

PARAM_SEPARATOR?=|

################################################
## Options for Gblocks
## Here: allow up to half the sequence to have gaps
PARAM_GBLOCKS_OPTIONS?=-b5=h

## Accept Gblocks alignments, if at least 50% of positions are kept,
## otherwise keep the original
PARAM_GBLOCKS_MIN_KEPT?=50

################################################
## Whether or not to filter the input alignment
## Possible options are: 
## 4d:      only four-fold degenerate sites
## 3rd:	    only third codon positions
## <empty>: no filtering (using codons)
PARAM_RESTRICT_ANALYSIS?=

################################################
# Section parameters: end
################################################
REQUISITES=input.species input.tree input.map

GENOMES_COMMA=`grep -v "^\#" input.species | xargs | perl -p -e "s/ +/,/g"`

#######################################################################################
#######################################################################################
#######################################################################################
## preparation of using all sets
#######################################################################################
data.prepare:
	$(PRELOG)
	$(MAKE) data.dir
	$(CMD_LOG) "creating directories and writing malis."
	@python $(DIR_SCRIPTS_TOOLS)malis2malis.py \
		--filename-components=input.map \
		--pattern-mali=$(PARAM_PATTERN_MALIS) \
	       	--pattern-component="^(\S+)" \
		--pattern-output="data.dir/cluster_%s.dir/cluster_%s.fasta" \
		--pattern-filter="^([^|]+)[|]" \
		--filename-filter=input.species \
		--output-format=fasta > $@
	$(CMD_LOG) "adding files to directories."
	@for d in data.dir/cluster_*.dir; do \
		cluster_id=$${d#data.dir/cluster_}; \
		cluster_id=$${cluster_id%.dir}; \
		ln -fs ../../Makefile $${d}/Makefile; \
		ln -fs ../../input.grammar $${d}/grammar; \
	done
	$(CMD_LOG) "adding trees to directories." 
	@python $(DIR_SCRIPTS_TOOLS)tree2tree.py \
		--method=add-node-names \
		--log=$@ \
	< $(PARAM_INPUT_FILENAME_TREES) |\
	python $(DIR_SCRIPTS_GENEPREDICTION)split_fasta.py \
		--output-pattern="data.dir/cluster_%s.dir/cluster_%s.tree" \
	>> $@	
	$(EPILOG)

#######################################################################################
#######################################################################################
#######################################################################################
## Progress report
#######################################################################################
data.show-progress:
	@echo "# prediction status at `date`" >> data.progress
	@nhook=0;nfasta=0;nxrate=0;ntree=0; \
	for d in data.dir/cluster*.dir; do \
		cluster_id=$${d#data.dir/cluster_}; \
		cluster_id=$${cluster_id%.dir}; \
		if test -s $${d}/cluster_$${cluster_id}.fasta; then let "nfasta=nfasta+1"; fi; \
		if test -s $${d}/cluster_$${cluster_id}.tree; then let "ntree=ntree+1"; fi; \
		if test -s $${d}/cluster_$${cluster_id}.xrate; then let "nxrate=nxrate+1"; fi; \
		if test -e $${d}/data.run-subhook; then let "nhook=nhook+1"; fi; \
	done; \
	awk -v nfasta="$${nfasta}" -v nxrate="$${nxrate}" -v nhook="$${nhook}" -v ntree="$${ntree}" \
	   'END {  printf("# N\tNTREE\tPLEFT\tRSUCC\tNXRATE\tPLEFT\tRSUCC\tNHOOK\tPLEFT\tRSUCC\n"); \
		printf("%i\t%i\t%5.2f\t%5.2f\t%i\t%5.2f\t%5.2f\t%i\t%5.2f\t%5.2f\n", \
			nfasta,\
			ntree,((nfasta-ntree)*100)/nfasta,(nfasta > 0) ? 100*ntree/nfasta : 0, \
			nxrate,((nfasta-nxrate)*100)/nfasta,(nfasta > 0) ? 100*nxrate/nfasta : 0, \
			nhook,((nfasta-nhook)*100)/nfasta,(nfasta > 0) ? 100*nhook/nfasta : 0 ); }' \
	</dev/null >> data.progress
	@tail data.progress

#######################################################################################
#######################################################################################
#######################################################################################
## Show missing files
#######################################################################################
data.show-unfinished:
	@for d in data.dir/cluster_*.dir; do \
		cluster_id=$${d#data.dir/cluster_}; \
		cluster_id=$${cluster_id%.dir}; \
		file=$${d}/cluster_$${cluster_id}.stk; \
		if test -e $${file} && ! grep -q "\/\/" $${file}; then \
			$(CMD_MSG2)  "unfinished $${file};"; \
		fi; \
		file=$${d}/cluster_$${cluster_id}_fixed_w_ml.tree; \
		if test -e $${file} && ! grep -q ";; end alphabet" $${file}; then \
			$(CMD_MSG2) "unfinished $${file};"; \
		fi; \
	done

#######################################################################################
#######################################################################################
#######################################################################################
## Build targets in subdirectories
#######################################################################################
DATA=$(wildcard cluster_[0-9]*.dir)

data.run: data.prepare
	$(PRELOG)
	@$(MAKE) -C data.dir -k -j $(PARAM_NUM_JOBS) $@-hook
	$(EPILOG)

$(DATA):
	@$(MAKE) -C $@ data.run-subhook 

data.run-hook: $(DATA)

data.run-subhook: 
	$(PRELOG)
	@$(CMD_REMOTE_SUBMIT) $(MAKE) data-hook < /dev/null 
	@touch $@
	$(EPILOG)

.PHONY: $(DATA)

#################################################################################
#################################################################################
#################################################################################
DATA_QUERIES_SUBDIR=$(wildcard *.fasta)
DATA_TARGETS_SUBDIR=$(DATA_QUERIES_SUBDIR:%.fasta=%.masked_mali) \
		$(DATA_QUERIES_SUBDIR:%.fasta=%.stk) \
		$(DATA_QUERIES_SUBDIR:%.fasta=%.xrate) 

data-hook: $(DATA_TARGETS_SUBDIR)

#################################################################################
#################################################################################
#################################################################################
## Mask sequences for composition and incomplete codons and remove fully gapped 
## columns
#################################################################################
%.masked_mali: %.fasta
	$(PRELOG)
	@python $(DIR_SCRIPTS_TOOLS)fasta2fasta.py --method=translate -v 0 < $< |\
	python $(DIR_SCRIPTS_TOOLS)fasta2fasta.py --method=mask-seg -v 0	> $@_tmp
	@python $(DIR_SCRIPTS_TOOLS)fasta2fasta.py \
		--method=mask-codons \
		--parameters=$@_tmp \
		--method=mask-incomplete-codons \
		--verbose=0 \
	< $*.fasta |\
	python $(DIR_SCRIPTS_TOOLS)mali2mali.py \
		--method=propagate-masks,remove-all-gaps,remove-empty-sequences \
		--mask-char="n" \
		--verbose=0 \
	> $@
	@rm -f $@_tmp
	$(EPILOG)

#################################################################################
#################################################################################
#################################################################################
## Run Gblocks on mali.
## Note: Gblocks always ends on error code 1, thus ignore it.
## If more than 50% is removed, keep the original alignment
#################################################################################
%.mali: %.masked_mali
	$(PRELOG)
	@rm -f $@.log
	@grep -v "#" $< |\
	perl -p -e "s/ //g" > $@_tmp
	@-Gblocks $@_tmp -t=c $(PARAM_GBLOCKS_OPTIONS) > $@.log
	@nkept=`grep "Gblocks alignment" $@.log | tail -n 1 | perl -p -e "s/.*positions \(//; s/ %\).*//;"`; \
	if [[ $${nkept} -lt "$(PARAM_GBLOCKS_MIN_KEPT)" ]]; then \
		printf "using original alignment\n" >> $@.log; \
		$(CMD_LOG2) "using original alignment"; \
		mv $@_tmp $@; \
	else \
		mv $@_tmp-gb $@; \
	fi; \
	rm -f $@_tmp*
	$(EPILOG)

#######################################################################################
#######################################################################################
#######################################################################################
## Prepare data for input
## 1. Convert mali to phylip format and perform the following operations on it:
##    Remove unaligned sequences
##    Rename identifiers in mali and tree to short identifiers
##    Remove alternative transcripts
##    Unroot tree
##    Remove everything but identifier
#######################################################################################
ifeq ($(PARAM_RESTRICT_ANALYSIS),4d)
EXTRA_FILTERS=,filter-4d
else
ifeq ($(PARAM_RESTRICT_ANALYSIS),3rd)
EXTRA_FILTERS=,filter-3rd
else
EXTRA_FITLERS=
endif
endif

%.stk: %.mali
	$(PRELOG)
	@python $(DIR_SCRIPTS_TOOLS)mali2mali.py \
		--method=remove-unaligned-pairs,remove-all-gaps$(EXTRA_FILTERS) \
		--output-format=stockholm \
		--verbose=0 \
	< $< |\
	perl -p -e "s/[$(PARAM_SEPARATOR)]\S+//" \
	> $@_tmp
	@perl $(DIR_SCRIPTS_IHTOOLS)addtree.pl \
		<(grep -v "^>" $*.tree) \
		$@_tmp > $@
	@rm -f $@_tmp
	$(EPILOG)

#######################################################################################
#######################################################################################
#######################################################################################
## Train the grammar
#######################################################################################
%.xrate: %.stk
	$(PRELOG)
	@xrate $< -g grammar -t $@ --noannotate -logfile $*.log -log 5 >/dev/null
	$(EPILOG)

#######################################################################################
#######################################################################################
#######################################################################################
## analysis targets
#######################################################################################
analysis: analysis.dir analysis.dir/results.table analysis.dir/results.stats

analysis.dir/results.table:
	$(PRELOG)
	@python $(DIR_SCRIPTS_GENEPREDICTION)xrate_gc.py \
		--filename-input-pattern=data.dir/cluster_*.dir/cluster*.xrate \
		--pattern-id="(\d+)" > $@
	$(EPILOG)

analysis.dir/results.stats: analysis.dir/results.table
	$(PRELOG)
	@python $(DIR_SCRIPTS_TOOLS)data2stats.py \
		--flat \
		< $< > $@
	$(EPILOG)

#######################################################################################
include $(DIR_SCRIPTS_GENEPREDICTION)/makefiles/Makefile.common

