################################################################################
#   Gene prediction pipeline 
#
#   $Id: Makefile.orthology_export_gbrowser 2781 2009-09-10 11:33:14Z andreas $
#
#   Copyright (C) 2005 Andreas Heger
#
#   This program is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License
#   as published by the Free Software Foundation; either version 2
#   of the License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#################################################################################

################################################
## Section parameters: start
################################################

################################################
## Export parameters for the genome browser gbrowse
PARAM_EXPORT_GBROWSER_USERNAME?=andreas

PARAM_EXPORT_GBROWSER_PASSWORD?=HeinBloed

PARAM_EXPORT_GBROWSER_HOST?=db

## prefix of tables, suffix is schema of species
PARAM_EXPORT_GBROWSER_DATABASE?=gbrowser_devel_

## separator
PARAM_EXPORT_GBROWSER_SEPARATOR?=_

PARAM_EXPORT_GBROWSER_ADD_PREFIX?=

################################################
## Section parameters: end
################################################

#############################################################################
## export statements for the genome browser
EXPORT_GBROWSER_TARGETS=export_gbrowser_orthologlinks.gff export_gbrowser_orthologlinks.load

export_gbrowser: 
	$(MAKE) $@.dir 
	$(MAKE) -C $@.dir $(EXPORT_GBROWSER_TARGETS)

EXPORT_GBROWSER_ORTHOLOGLINKS_TRACK=	\
				f.sbjct_token, \
			   	'gpipe', \
			   	'ortho_$${target}' , \
			   	CASE WHEN f.sbjct_strand = '+' THEN f.sbjct_genome_from+c.start \
	     				WHEN f.sbjct_strand = '-' THEN c.size-f.sbjct_genome_to+c.start END, \
			   	CASE WHEN f.sbjct_strand = '+' THEN f.sbjct_genome_to+c.start \
	     				WHEN f.sbjct_strand = '-' THEN c.size-f.sbjct_genome_from+c.start END, \
				l.weight, \
				f.sbjct_strand, \
				'.',

EXPORT_GBROWSER_ORTHOLOGLINKS_FROM=	\
			    FROM $(PARAM_TABLE_NAME_ORTHOLOGLINKS)_first AS l, \
			    $$f.predictions AS f, \
			    $$t.predictions AS t, \
			    $$f.contigs AS c 

EXPORT_GBROWSER_ORTHOLOGLINKS_WHERE=	\
			c.sbjct_token = f.sbjct_token 

EXPORT_GBROWSER_ID1=l.schema1 || '$(PARAM_EXPORT_GBROWSER_SEPARATOR)' || l.gene_id1 
EXPORT_GBROWSER_ID2=l.schema2 || '$(PARAM_EXPORT_GBROWSER_SEPARATOR)' || l.gene_id2 

ifneq ($(PARAM_EXPORT_GBROWSER_ADD_PREFIX),)
CMD_PREFIX=`echo $${schema} | perl -p -e "s/vs_.*//"`
CMD_SUBSTITUTE1=|perl -p -e "if(/^>/ && !/$${prefix}/) { s/>/>$${prefix}/; }"
CMD_SUBSTITUTE2=|perl -p -e "if(!/^$${prefix}/) { s/^/$${prefix}/; s/Contig /Contig $${prefix}/; }" 
CMD_SUBSTITUTE3=|perl -p -e "if(!/^$${prefix}/) { s/^/$${prefix}/; }" 
else
CMD_PREFIX=
CMD_SUBSTITUTE1=
CMD_SUBSTITUTE2=
endif

## Added patch at the end to map contigs for the fly genome
## project.
## Printing orthologs out doubly, not quite sure, why this is necessary
export_gbrowser_orthologlinks.gff:
	$(PRELOG)
	@for f in $(PARAM_SRC_SCHEMAS); do \
		prefix=$(CMD_PREFIX); \
		for t in $(PARAM_SRC_SCHEMAS); do \
			if [[ "$$f" != "$$t" ]]; then \
			    $(CMD_LOG2) "processing pair from=$$f to=$$t."; \
			    target=$${t}; \
			    $(PSQL_CONNECTION) \
			    "SELECT $(EXPORT_GBROWSER_ORTHOLOGLINKS_TRACK) \
			    'Ortholog ' || $(EXPORT_GBROWSER_ID2) || ' ; ' || \
			    'Note ' || 	l.gd1 || 'x' || l.gd2 \
				    || '-' || \
					l.td1 || 'x' || l.td2 \
				    || ' ; ' \
			    $(EXPORT_GBROWSER_ORTHOLOGLINKS_FROM) \
			    WHERE $(EXPORT_GBROWSER_ORTHOLOGLINKS_WHERE) AND\
				f.prediction_id = l.prediction_id1 AND \
			    	t.prediction_id = l.prediction_id2 AND \
			  	l.schema1 = '$$f' AND l.schema2 = '$$t' \
			    GROUP BY l.schema2, l.gene_id2, c.start, c.size, l.gd1, l.gd2, l.td1, l.td2, \
				f.sbjct_strand, f.sbjct_token, f.sbjct_genome_from, f.sbjct_genome_to, l.weight" \
			    $(PSQL_CONNECTION_OPTIONS) |\
			    grep -v "#" $(CMD_SUBSTITUTE2) \
			    > $@.$${f}-versus-$${t}.gff; \
			fi; \
		done; \
	done;
	@touch $@
	$(EPILOG)


# 			    $(PSQL_CONNECTION) \
# 			    "SELECT $(EXPORT_GBROWSER_ORTHOLOGLINKS_TRACK) \
# 			    'Ortholog ' || $(EXPORT_GBROWSER_ID1) || ' ; ' || \
# 			    'Note ' || \
# 					l.gd1 || 'x' || l.gd2 || '-' || \
# 					l.td1 || 'x' || l.td2 \
# 		 		|| ' ; ' \
# 			    $(EXPORT_GBROWSER_ORTHOLOGLINKS_FROM) \
# 			    WHERE $(EXPORT_GBROWSER_ORTHOLOGLINKS_WHERE) AND\
# 				f.prediction_id = l.prediction_id2 AND \
# 			    	t.prediction_id = l.prediction_id1 AND \
# 				l.schema2 = '$$f' AND l.schema1 = '$$t' \
# 			    GROUP BY l.schema1, l.gene_id1, c.start, c.size, l.gd1, l.gd2, l.td1, l.td2, \
# 				f.sbjct_strand, f.sbjct_token, f.sbjct_genome_from, f.sbjct_genome_to, l.weight" \
# 			    $(PSQL_CONNECTION_OPTIONS) |\
# 			    perl -p -e "if(!/^$${prefix}/) { s/^/$${prefix}/; }" \
# 			    >> $@.$${f}-versus-$${t}.gff; \

export_gbrowser_orthologlinks_%.load: export_gbrowser_orthologlinks.gff
	$(PRELOG)
	@f=$*; \
	for t in $(PARAM_SRC_SCHEMAS); do \
		if [[ "$$f" != "$$t" ]]; then \
		    $(CMD_LOG2) "processing pair from=$$f to=$$t."; \
		    bp_fast_load_gff.pl \
			--user $(PARAM_EXPORT_GBROWSER_USERNAME) \
			--pass $(PARAM_EXPORT_GBROWSER_PASSWORD) \
			-d $(PARAM_EXPORT_GBROWSER_DATABASE)$${f} \
			export_gbrowser_orthologlinks.gff.$${f}-versus-$${t}.gff 2>> $@; \
		fi; \
	done
	$(EPILOG)

export_gbrowser_orthologlinks.load: export_gbrowser_orthologlinks.gff
	$(PRELOG)
	@for f in $(PARAM_SRC_SCHEMAS); do \
		for t in $(PARAM_SRC_SCHEMAS); do \
			if [[ "$$f" != "$$t" ]]; then \
			    $(CMD_LOG2) "processing pair from=$$f to=$$t."; \
			    bp_fast_load_gff.pl \
				--user $(PARAM_EXPORT_GBROWSER_USERNAME) \
				--pass $(PARAM_EXPORT_GBROWSER_PASSWORD) \
				-d $(PARAM_EXPORT_GBROWSER_DATABASE)$${f} \
				export_gbrowser_orthologlinks.gff.$${f}-versus-$${t}.gff 2>> $@; \
			fi; \
		done; \
	done
	$(EPILOG)
