################################################################################
#
#   Gene prediction pipeline 
#
#   $Id: Makefile.bootstrap 2781 2009-09-10 11:33:14Z andreas $
#
#   Copyright (C) 2005 Andreas Heger
#
#   This program is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License
#   as published by the Free Software Foundation; either version 2
#   of the License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#################################################################################
##
## Perform bootstrap analysis on a multiple alignment
##
## Allowed variations:
##
##	Distance matrix based tree building algorithms
##	from the phylip package
##	1. tree building method fitch, kitsch, neighbor
##
##	2. distance matrices
##	
##	1. Distance implemented in dnadist from PHYLIP
##	2. ks based distance measurement
##
##	Note: the input multiple alignment should be free
##		of frameshifts and stop-codons.	 	
################################################ 

################################################
## Section parameters: start
################################################

################################################
## project name
PARAM_PROJECT_NAME?=

## number of bootstrap samples
PARAM_BOOTSTRAP_NUM_SAMPLES?=100

################################################
## tree building method for bootstrap
PARAM_BOOTSTRAP_TREE_METHOD?=kitsch

################################################
## method for distance calculation
PARAM_BOOTSTRAP_DISTANCE_METHOD?=F84

################################################
PARAM_BOOTSTRAP_MAX_DISTANCE?=100

################################################
## Section parameters: end
################################################

#######################################################################
#######################################################################
#######################################################################
## 1. translate alignment and build boostrap samples
#######################################################################
bootstrap.prepare: input.mali
	$(PRELOG)
	@$(MAKE) samples.dir
	@python $(DIR_SCRIPTS_TOOLS)mali2bootstrap.py \
		--samples=$(PARAM_BOOTSTRAP_NUM_SAMPLES) \
		--block-size=3 \
		--output-filename-pattern="samples.dir/sample_%05i.fasta" \
	< $< > $@
	$(EPILOG)

#######################################################################
#######################################################################
#######################################################################
bootstrap.run: bootstrap.prepare
	$(PRELOG)
	@$(MAKE) -j $(PARAM_NUM_JOBS) -k -C samples.dir bootstrap.run-hook
	$(EPILOG)


#######################################################################
#######################################################################
#######################################################################
bootstrap.finish: bootstrap.run consensus.tree

#######################################################################
#######################################################################
#######################################################################
## 3. build distance matrices and trees.
#######################################################################
BOOTSTRAP_QUERIES=$(wildcard sample_*.fasta)
BOOTSTRAP_TARGETS=$(BOOTSTRAP_QUERIES:%.fasta=%.distances) $(BOOTSTRAP_QUERIES:%.fasta=%.tree)

bootstrap.run-hook: $(BOOTSTRAP_TARGETS)

%.distances: %.fasta
	$(PRELOG)
	@$(CMD_REMOTE_SUBMIT) \
	python $(DIR_SCRIPTS_GENEPREDICTION)mali2rates.py \
		--distance=$(PARAM_BOOTSTRAP_DISTANCE_METHOD) \
	< $< > $@
	$(EPILOG)

%.tree: %.distances
	$(PRELOG)
	@python $(DIR_SCRIPTS_TOOLS)csv_cut.py seq1 seq2 dist \
	< $< |\
	awk '$$3 <= $(PARAM_BOOTSTRAP_MAX_DISTANCE)' |\
	$(CMD_REMOTE_SUBMIT) \
	"python $(DIR_SCRIPTS_TOOLS)sparse2full.py \
		--output-format=phylip-replicates \
		--default-diagonal=0 \
		--default=0 |\
	python $(DIR_SCRIPTS_TOOLS)matrix2tree.py \
		--replicates \
		--method=$(PARAM_BOOTSTRAP_TREE_METHOD)" \
	> $@



#######################################################################
#######################################################################
#######################################################################
## Build consensus tree
#######################################################################
consensus.tree:
	$(PRELOG)
	-rm -rf $@.dir
	mkdir $@.dir
	find samples.dir -name "*.tree" -exec grep -v "#" {} \; |\
	python $(DIR_SCRIPTS_TOOLS)tree2tree.py \
		--method=build-map \
		--parameters=$@.map \
		--log=$@.log \
		--verbose=0 \
	> $@.dir/intree
	cd $@.dir; echo -e "Y\n" | consense >> $@.log
	@cat $@.dir/outfile >> $@.log
	python $(DIR_SCRIPTS_TOOLS)tree2tree.py \
		--method=rename \
		--invert-map \
		--parameters=$@.map \
	< $@.dir/outtree > $@
	rm -rf $@.dir
	$(EPILOG)



###############################################################################
include $(DIR_SCRIPTS_GENEPREDICTION)/makefiles/Makefile.common
