################################################################################
#   Gene prediction pipeline 
#
#   $Id: Makefile.step9 2029 2008-07-15 09:18:30Z andreas $
#
#   Copyright (C) 2004 Andreas Heger
#
#   This program is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License
#   as published by the Free Software Foundation; either version 2
#   of the License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#################################################################################

##############################################################################
# compute correspondence between exon boundaries in query and predicted exon boundaries.
##############################################################################
step9: step8 step9.exons step9.exons.load step9.overlaps step9.overlaps.load $(STEP9_TARGETS)
	@touch $@
	$(EPILOG)

##############################################################################
## Exon comparison
##############################################################################
step9.exons: step8.predictions.gz
	$(PRELOG)
	@$(CMD_REMOTE_SUBMIT) \
	"gunzip < $< | sort -k{3,3} |\
	python $(DIR_SCRIPTS_GENEPREDICTION)gpipe/compare_predictions2exons.py \
		$(PYTHON_OPTIONS) \
		--peptides=$(STEP8_MERGE_PEPTIDES) \
		--boundaries=reference.exons \
		--exons=$@ \
		--genome-file=$(PARAM_ASSEMBLY_PATTERN) \
		--quality-pide=$(PARAM_QUALITY_GOOD_EXON_THRESHOLD) \
		--write-notfound" \
	< /dev/null > $@_summary
	$(EPILOG)

step9.exons.load: step9.exons
	$(PRELOG)
	@$(CONNECTION) "DELETE FROM $(PARAM_TABLE_NAME_EXONS);" > /dev/null
	@$(CONNECTION) "DELETE FROM $(PARAM_TABLE_NAME_EXONS_SUMMARY);" > /dev/null
	@grep -v -e "#" -e "prediction_id" $<_summary | sort -k{1,1}n |\
	$(CONNECTION) "COPY $(PARAM_TABLE_NAME_EXONS_SUMMARY) FROM STDIN WITH NULL AS 'na'" > $@ 
	@grep -v -e "#" -e "prediction_id" $< |\
	$(CONNECTION) "COPY $(PARAM_TABLE_NAME_EXONS) FROM STDIN WITH NULL AS 'na'" >> $@ 
	$(CMD_LOG) "loaded into $(PARAM_TABLE_NAME_EXONS_SUMMARY): `$(CONNECTION) 'SELECT COUNT(*) FROM $(PARAM_TABLE_NAME_EXONS_SUMMARY);' -t `"
	$(CMD_LOG) "loaded into $(PARAM_TABLE_NAME_EXONS): `$(CONNECTION) 'SELECT COUNT(*) FROM $(PARAM_TABLE_NAME_EXONS);' -t `"  
	$(CMD_LOG) "# Exon information" 
	$(CMD_LOG) "available predictions `$(CONNECTION) 'SELECT COUNT(DISTINCT prediction_id) FROM $(PARAM_TABLE_NAME_EXONS);' -t `" 
	@touch $@
	$(EPILOG)

##############################################################################
## The making of genes
##############################################################################
step9.overlaps: step8 step9.exons step9.exons.load step9.overlaps.matches step9.overlaps.load 
	@touch $@
	$(EPILOG)

step9.predictions.fasta: step8.predictions.gz
	$(PRELOG)
	@gunzip < $< | awk '!/^#/ {printf(">%s\n%s\n", $$1, $$22); }' |\
	python $(DIR_SCRIPTS_TOOLS)index_fasta.py step9.predictions - > $@.log
	$(EPILOG)	

## 2. Overlaps are defined by exon overlap of good exons.
## the alignment between two transcripts is checked as well.
step9.overlaps.matches: step9.exons.load step9.predictions.fasta
	$(PRELOG)
	@$(CONNECTION) \
	"SELECT p.prediction_id, p.sbjct_token, p.sbjct_strand, \
	e.exon_frame, 0, e.exon_from, e.exon_to, e.genome_exon_from, e.genome_exon_to \
	FROM $(PARAM_TABLE_NAME_PREDICTIONS) AS p, $(PARAM_TABLE_NAME_EXONS) AS e \
	WHERE p.prediction_id = e.prediction_id AND \
	e.is_ok = TRUE AND e.exon_to > 0" \
	$(CONNECTION_OPTIONS) |\
	$(CMD_REMOTE_SUBMIT) \
	python $(DIR_SCRIPTS_GENEPREDICTION)gpipe_gpipe/exonerate_combine_regions.py \
	--peptides=step9.predictions.fasta \
	--alignment=80.0 \
	--overlap=1 > $@
	$(EPILOG)

## 3. load overlaps. Gene is set to 0.
## add genes for sequences without reference exon information.
step9.overlaps.load: step9.overlaps.matches
	$(PRELOG)
	@$(CONNECTION) "DELETE FROM $(PARAM_TABLE_NAME_GENES);" > /dev/null
	@grep -v -e "^#" -e "^rep" step9.overlaps.matches | awk '{printf("%s\t%s\t%s\n", $$2, 0, $$1);}' | sort -k1,1n |\
	$(CONNECTION) "COPY $(PARAM_TABLE_NAME_GENES) FROM STDIN WITH NULL AS 'na'" > $@ 
	$(CMD_LOG) "loaded into $(PARAM_TABLE_NAME_GENES): `$(CONNECTION) 'SELECT COUNT(*) FROM $(PARAM_TABLE_NAME_GENES);' -t `" 
	@$(CONNECTION) "INSERT INTO $(PARAM_TABLE_NAME_GENES) \
	(prediction_id, gene_id, overlap_id) \
	SELECT p.prediction_id, 0, p.prediction_id FROM $(PARAM_TABLE_NAME_PREDICTIONS) AS p \
	LEFT JOIN $(PARAM_TABLE_NAME_GENES) AS g \
	ON p.prediction_id = g.prediction_id \
	WHERE g.prediction_id IS NULL" > /dev/null
	@rm -f $@.tmp1 $@.tmp2
	@touch $@
	$(EPILOG)
