################################################################################
#   OPTIC: Orthology prediction pipeline
#
#   $Id: Makefile.optic 2781 2009-09-10 11:33:14Z andreas $
#
#   Copyright (C) 2008 Andreas Heger
#
#   This program is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License
#   as published by the Free Software Foundation; either version 2
#   of the License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#################################################################################
##
## control makefile for optic
##
################################################
## Section parameters: start
################################################
## project name
PARAM_PROJECT_NAME?=geneprediction

PARAM_DIR_UPLOAD?=/home/andreas/uploads/

PARAM_PSQL_SCHEMA?=$(PARAM_PROJECT_NAME)

################################################
# Section parameters: end
################################################

## methods: correspond to makefile suffixes
METHODS=gpipe_export \
	orthology_pairwise_multiple \
	orthology_multiple \
	orthology_malis \
	paralogy_trees \
	paralogy_rates \
	codeml_kaks

## directories to use
DIRS=export \
	orthology_pairwise \
	orthology_multiple \
	malis \
	paralogy_trees \
	paralogy_rates \
	phylogeny

################################################
#
# Setup directories
#
################################################

prepare: create-schema
	@dirs=($(DIRS)); \
	methods=($(METHODS)); \
	for ((x = 0; x < $${#dirs[@]}; ++x)); do \
		method=$${methods[$$x]}; \
		dir=$${dirs[$$x]}; \
		python $(DIR_SCRIPTS_GENEPREDICTION)gpipe/setup.py \
			--force \
			--method=$${method} \
			--project=$(PARAM_PROJECT_NAME)_$${dir} \
			--dest=$(CURDIR)/$${dir} \
			--rootdir=$(DIR_ROOT) \
			--include=$(CURDIR)/data/Makefile.inc >> $@; \
	done

#########################################################################
create-schema:
	$(PRELOG)
	-@$(PSQL_CONNECTION) "CREATE SCHEMA $(PARAM_PSQL_SCHEMA)" $(TO_NULL)
	$(EPILOG)

#########################################################################
include $(DIR_SCRIPTS_GENEPREDICTION)/makefiles/Makefile.common

